substitutions:
  name: victron-esp32-direct
  device_description: "Victron MPPT 150/45 via VE.Direct v1.2.7"
  friendly_name: "Victron"
  version: "1.2.7"

esphome:
  name: ${name}
  comment: ${device_description}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  baud_rate: 0
  level: INFO

api:
  encryption:
    key: "ONO5iD72Y1IU9ArplCJuKsozX48v8aVZmlEW0hTq6Zg="

ota:
  - platform: esphome
    password: "01082f94b369f8ad6d1ce610941b57a8"
  - platform: web_server

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# ============================================
# NTP TIME SYNC - time.google.com AST -4
# ============================================  
time:
  - platform: sntp
    id: sntp_time
    timezone: AST4
    servers:
      - time.google.com
      - pool.ntp.org
    update_interval: 4h
    on_time_sync:
      then:
        - logger.log: "Time synchronized with NTP server"

# ============================================
# VE.Direct UART2 Configuration
# ============================================
uart:
  id: uart_0
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 19200
  rx_buffer_size: 256

external_components:
  - source: github://KinDR007/VictronMPPT-ESPHOME@main
    refresh: 0s

victron:
  id: victron0
  uart_id: uart_0

# ================================
# SENSORS - ORGANIZED BY CATEGORY
# ================================
sensor:
  # ========================================
  # CATEGORÍA: ENERGY DASHBOARD (Principal)
  # ========================================
  
  # POTENCIA INSTANTÁNEA (kW)
  - platform: template
    name: "Solar Power"
    id: solar_power_kw
    device_class: power
    state_class: measurement
    unit_of_measurement: "kW"
    accuracy_decimals: 2
    lambda: |-
      if (id(panel_power).has_state()) {
        return id(panel_power).state / 1000.0;
      }
      return 0.0;
    update_interval: 10s

  # ENERGÍA DEL DÍA (kWh) - Reset a medianoche
  - platform: total_daily_energy
    name: "Solar Energy Today"
    id: solar_energy_today
    power_id: panel_power
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    filters:
      - multiply: 0.001

  # ====================
  # CATEGORÍA: BATTERY 
  # ====================
  
  - platform: victron
    victron_id: victron0
    battery_voltage:
      name: "Battery Voltage"
      id: battery_voltage
      accuracy_decimals: 2
    battery_current:
      name: "Battery Current"
      id: battery_current
      accuracy_decimals: 2

  # ========================
  # CATEGORÍA: SOLAR PANELS 
  # ========================
  
  - platform: victron
    victron_id: victron0
    panel_voltage:
      name: "Panel Voltage"
      id: panel_voltage
      accuracy_decimals: 2
    panel_power:
      name: "Panel Power"
      id: panel_power

  - platform: template
    name: "Panel Current"
    id: panel_current
    device_class: current
    state_class: measurement
    unit_of_measurement: "A"
    accuracy_decimals: 2
    lambda: |-
      if (id(panel_voltage).has_state() && id(panel_voltage).state > 0 &&
          id(panel_power).has_state() && id(panel_power).state > 0) {
        return id(panel_power).state / id(panel_voltage).state;
      }
      return 0.0;
    update_interval: 10s

  # ===================================
  # CATEGORÍA: YIELD (Producción MPPT)
  # ===================================
  
  - platform: victron
    victron_id: victron0
    yield_today:
      name: "Yield Today"
      id: yield_today
      accuracy_decimals: 2
    yield_yesterday:
      name: "Yield Yesterday"
      id: yield_yesterday
      accuracy_decimals: 2
   #yield_total:
   #  name: "Yield Total"
   #  id: yield_total
    max_power_today:
      name: "Max Power Today"
      id: max_power_today
    max_power_yesterday:
      name: "Max Power Yesterday"
      id: max_power_yesterday
    day_number:
      name: "Day Number"
      id: day_number

  # =======================
  # CATEGORÍA: DIAGNOSTIC 
  # =======================
  
  - platform: uptime
    id: uptime_seconds
    internal: true
    update_interval: 60s

  - platform: wifi_signal
    name: "ESP32 WiFi Signal"
    entity_category: diagnostic
    update_interval: 60s

# ===============
# BINARY SENSORS
# ===============
binary_sensor:
  - platform: status
    name: "ESP32 Status"
    entity_category: diagnostic

# ============================================
# TEXT SENSORS - ORGANIZED BY CATEGORY
# ============================================
text_sensor:
  # =======================
  # CATEGORÍA: MPPT STATUS
  # =======================
  
  - platform: victron
    victron_id: victron0
    charging_mode:
      name: "Charging Mode"
      id: charging_mode
    error:
      name: "Error"
      id: error
    tracking_mode:
      name: "Tracking Mode"
      id: tracking_mode
    firmware_version:
      name: "Firmware Version"
      id: firmware_version
      entity_category: diagnostic
    serial_number:
      name: "Serial Number"
      id: serial_number
      entity_category: diagnostic

  # =======================
  # CATEGORÍA: DIAGNOSTIC 
  # =======================
  
  - platform: template
    name: "ESP32 Uptime"
    icon: mdi:clock-start
    entity_category: diagnostic
    update_interval: 60s
    lambda: |-
      int seconds = (int)id(uptime_seconds).state;
      int days = seconds / 86400;
      int hours = (seconds % 86400) / 3600;
      int minutes = (seconds % 3600) / 60;
      int secs = seconds % 60;

      std::string result = "";
      if (days > 0) result += to_string(days) + "d ";
      if (hours > 0) result += to_string(hours) + "h ";
      if (minutes > 0) result += to_string(minutes) + "m ";
      result += to_string(secs) + "s";

      return result;

  - platform: template
    name: "ESP32 Date"
    icon: mdi:calendar-clock
    entity_category: diagnostic
    update_interval: 60s
    lambda: |-
      auto time = id(sntp_time).now();
      if (!time.is_valid()) {
        return {"Syncing..."};
      }

      int month = time.month;
      int day = time.day_of_month;
      int year = time.year;
      int hour = time.hour;
      int minute = time.minute;

      std::string am_pm = "am";
      int hour_12 = hour;

      if (hour == 0) {
        hour_12 = 12;
      } else if (hour == 12) {
        am_pm = "pm";
      } else if (hour > 12) {
        hour_12 = hour - 12;
        am_pm = "pm";
      }

      char buffer[30];
      snprintf(buffer, sizeof(buffer), "%d/%d/%d %d:%02d %s",
               month, day, year, hour_12, minute, am_pm.c_str());

      return {buffer};

  - platform: wifi_info
    ip_address:
      name: "ESP32 IP Address"
      entity_category: diagnostic
    ssid:
      name: "ESP32 WiFi SSID"
      entity_category: diagnostic
    mac_address:
      name: "ESP32 MAC Address"
      entity_category: diagnostic

  - platform: template
    name: "ESP32 Config Version"
    entity_category: diagnostic
    lambda: |-
      return {"${version}"};
