substitutions:
  name: victron-ble
  device_description: "Monitor a Victron MPPT Charge Controller via BLE v1.2"
  smart_solar_mac_address: cd:ac:27:2c:7d:41
  friendly_name: "Victron ESP32 BLE"
  version: "1.2"
  smart_solar_encryption_key: 64ca1f66c38f5d108e03b8b1ba4482d1

esphome:
  name: ${name}
  comment: ${device_description}
  friendly_name: ${friendly_name}

external_components:
  - source: github://Fabian-Schmidt/esphome-victron_ble

esp32:
  board: esp32dev
  framework:
    type: esp-idf

api:
  encryption:
    key: "fXi+MbBEylghmaKLe/MAKhXLaZmRG06Ct0HPWY++ZpI="

ota:
  - platform: esphome
    password: "8a6bce13393a2c29616b290a0d020908"
  - platform: web_server

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80
  
logger:
  level: INFO
  
esp32_ble_tracker:

victron_ble:
  - id: MySmartSolar
    mac_address: ${smart_solar_mac_address}
    bindkey: ${smart_solar_encryption_key}

sensor:
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "Victron Battery Voltage"
    type: BATTERY_VOLTAGE
    
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "Victron Battery Current"
    type: BATTERY_CURRENT
  
  # PV Power - Configurado para Energy Dashboard
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "Victron PV Power"              # ← NOMBRE ACTUALIZADO
    id: pv_power
    type: PV_POWER
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "Victron Yield Today"
    type: YIELD_TODAY
  
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "Victron Load Current"
    type: LOAD_CURRENT
  
  # Solar Energy - Configurado para Energy Dashboard
  - platform: integration
    name: "Victron Energy Produced"       # ← NOMBRE ACTUALIZADO
    sensor: pv_power
    unit_of_measurement: "kWh"
    time_unit: h 
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing
  
  - platform: wifi_signal
    name: "Victron WiFi Signal"
    update_interval: 60s
    
  - platform: uptime
    name: "Victron Uptime"

binary_sensor:
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "Victron MPPT Fault"
    type: DEVICE_STATE_FAULT
    
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "Victron MPPT Error"
    type: CHARGER_ERROR
  
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "Victron MPPT in BULK"
    type: DEVICE_STATE_BULK
    
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "Victron MPPT in ABSORPTION"
    type: DEVICE_STATE_ABSORPTION
    
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "Victron MPPT in FLOAT"
    id: mppt_in_float
    type: DEVICE_STATE_FLOAT

text_sensor:
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "Victron MPPT State"
    type: DEVICE_STATE
    
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "Victron MPPT Error Reason"
    type: CHARGER_ERROR
  
  - platform: wifi_info
    ip_address:
      name: "Victron ESP32 IP"
    ssid:
      name: "Victron WiFi SSID"    